Updated dblabels to correspond to db
bedapub/besca pull request #336
Opened 2024-01-12 11:42 UTC by swalpe

Adjusted dblabel nomenclature table to include the full updated kidney hierarchy as well as a few additional terms that were missing + removed some obsolute terms & changed animal cell => cell, as per CL update. Pls double-check that it works for you & I didn't introduce formatting errors.

2024-01-12 14:09 UTC, hatjek requested changes
Thank you for the update Petra! I saw some quotation marks in the new file (e.g. lines 2, 93, 94). Could you please remove them before merging these changes?

2024-01-25 13:30 UTC, swalpe commented
Indeed, thnx a lot for checking. Should be removed now, let me know if it looks k to merge!

2024-01-25 13:32 UTC, hatjek approved these changes
Yes, looks good, thank you!

2024-01-25 13:47 UTC, kohleman approved these changes

2024-01-25 13:47 UTC, merged